### ISSUE TITLE
(x + width) outside raster

### ISSUE THREAD

**Issue by tdiprima** [SBU-BMI/QuIPutils#3]
```
java.awt.image.RasterFormatException: (x + width) is outside raster
	at sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:467)
	at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
	at edu.stonybrook.bmi.quiputils.CustomTiler$PolyThread.run(CustomTiler.java:858)
```

**Comment by tdiprima** [comment]
Testing image TCGA-50-5066-01Z-00-DX1.

**Comment by tdiprima** [comment]
Fixed.  Commit [56e4b0e](https://github.com/SBU-BMI/QuIPutils/commit/56e4b0ecdbbd9eec77de1189f3d1449f05c5c817).
