### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by tdiprima** [SBU-BMI/QuIPutils#4]
```
Exception in thread "Thread-4718" java.lang.IndexOutOfBoundsException
	at java.io.RandomAccessFile.readBytes(Native Method)
	at java.io.RandomAccessFile.read(RandomAccessFile.java:377)
	at javax.imageio.stream.FileImageInputStream.read(FileImageInputStream.java:117)
	at com.sun.imageio.plugins.common.SubImageInputStream.read(SubImageInputStream.java:61)
	at com.sun.imageio.plugins.common.InputStreamAdapter.read(InputStreamAdapter.java:47)
	at java.io.SequenceInputStream.read(SequenceInputStream.java:207)
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at com.sun.imageio.plugins.png.PNGImageReader.decodePass(PNGImageReader.java:1112)
	at com.sun.imageio.plugins.png.PNGImageReader.decodeImage(PNGImageReader.java:1223)
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1338)
	at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1614)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at edu.stonybrook.bmi.quiputils.CustomTiler$PolyThread2.run(CustomTiler.java:751)
```

**Comment by tdiprima** [comment]
Tested a number of times...
Image TCGA-44-6778-01Z-00-DX1, analysis `wsi:r0.9:w0.8:l3:u200:k20:j0`.
Fails intermittently.
```
File image1...
BufferedImage ... = ImageIO.read(image1)
```
It creates a new file (eg. `TCGA-44-3398-01Z-00-DX1-6-0-0.png`) but when it tries to read it into a BufferedImage, the `ImageIO.read` fails.

Method `iCheck()` checks for the existence of the `File`, and if it doesn't exist, it creates it.
Original error could possibly be due to system pause between the checking and the writing.

**Comment by tdiprima** [comment]
Fixed.  Commit [56e4b0e](https://github.com/SBU-BMI/QuIPutils/commit/56e4b0ecdbbd9eec77de1189f3d1449f05c5c817).
